### ISSUE TITLE
안녕하십니까 교수님

### ISSUE THREAD

**Issue by kochanha** [sejongresearch/AdvancedC#2]
고급C 신청합니다.
Github ID: kochanha
email: ko1158@naver.com
감사합니다!

**Comment by unizard** [comment]
@kochanha 
멤버로 추가하였고, 아래의 private에 접근 가능할 겁니다.
https://github.com/sejongresearch/2019.Fall.AdvancedC

**Comment by unizard** [comment]
깃허브 이메일로 초대메일이 갔을겁니다.

2020년 6월 25일 (목) 오후 7:19, Chanyoung Kim <notifications@github.com>님이 작성:

**Comment by unizard** [comment]
@kochanha OJ 실명가입을 하지 않아 삭제조치 하였습니다. 재 가입시 반드시 실명을 지켜주세요
