### ISSUE TITLE
안녕하십니까 교수님

### ISSUE THREAD

**Issue by dysonny** [sejongresearch/AdvancedC#3]
고급 C github 신청합니다.
ID는 ssoony1 이며 Email은 denny221@naver.com 입니다.
감사합니다.

**Comment by unizard** [comment]
@ssoony1 
멤버로 추가하였고, 아래의 private에 접근 가능할 겁니다.
https://github.com/sejongresearch/2019.Fall.AdvancedC

**Comment by unizard** [comment]
깃허브 이메일로 초대메일이 갔을겁니다.

2020년 6월 26일 (금) 오후 11:04, 쏘니 <notifications@github.com>님이 작성:
